bee_user:
    resource: "@BEEUserBundle/Controller/"
    type:     annotation
    prefix:   /

bee_back_office_beeease:
    resource: "@BEEBackOfficeBeeeaseBundle/Controller/"
    type:     annotation
    prefix:   /



bee_services_beeease:
    resource: "@BEEServicesBeeeaseBundle/Controller/"
    type:     annotation
    prefix:   /
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting


fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile




