<?php

namespace BEE\Services\BeeeaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DisparitionReineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisparitionReineRepository extends EntityRepository
{
}
