<?php

namespace BEE\Services\BeeeaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FabricationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FabricationRepository extends EntityRepository
{
}
